AllCops:
  DisplayCopNames: true

#
# Metrics
#

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

#
# Style
#

Style/StringLiterals:
  EnforcedStyle: double_quotes
