AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5

#
# Metrics
#

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 100

Metrics/LineLength:
  Max: 128

Metrics/MethodLength:
  Max: 25

#
# Naming
#

Naming/MethodParameterName:
  Enabled: false

#
# Style
#

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
